version: "3.7"
networks:
  neuronation:
    driver: bridge
services:
  db:
    image: mysql:8.0
    container_name: neuronation-db
    restart: always
    environment:
      MYSQL_DATABASE: neuronation
      MYSQL_ROOT_PASSWORD: n3ur0n4t10n
      MYSQL_PASSWORD: n3ur0n4t10n
      MYSQL_USER: neuronation
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - neuronation
  app:
    build:
      args:
        user: neuronation
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: neuronation
    container_name: neuronation-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - neuronation
  nginx:
    image: nginx:1.17-alpine
    container_name: neuronation-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - neuronation






